name: Secret Scanning (Gitleaks)

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Secret Scanning (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106ea9b10d6a4d1fac674511ebb0f7c506ea
